import { type AppType } from "next/dist/shared/lib/utils";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import Navbar from "~/components/Navbar";

import "~/styles/globals.css";
import "react-toastify/dist/ReactToastify.css";
import Footer from "~/components/Footer";
import { Analytics } from '@vercel/analytics/react';

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <div className="flex min-h-screen flex-col">
      <Head>
        <title>Chat With Your Favorite YouTuber</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex-grow">
        <Navbar />
        <Component {...pageProps} />
      </div>
      <Footer />
      <ToastContainer />
      <Analytics />
    </div>
  );
};

export default MyApp;
